# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STTwitterDebounceDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for STTwitterDebounceDemo
  pod 'STTwitter'
  pod 'LBTATools'
  pod 'SDWebImage'

end
